// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event/eventpb/event.proto

package eventpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateEvent struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	User                 string   `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Timestamp            string   `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEvent) Reset()         { *m = CreateEvent{} }
func (m *CreateEvent) String() string { return proto.CompactTextString(m) }
func (*CreateEvent) ProtoMessage()    {}
func (*CreateEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c88e0126701e74a, []int{0}
}

func (m *CreateEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEvent.Unmarshal(m, b)
}
func (m *CreateEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEvent.Marshal(b, m, deterministic)
}
func (m *CreateEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEvent.Merge(m, src)
}
func (m *CreateEvent) XXX_Size() int {
	return xxx_messageInfo_CreateEvent.Size(m)
}
func (m *CreateEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEvent.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEvent proto.InternalMessageInfo

func (m *CreateEvent) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *CreateEvent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateEvent) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *CreateEvent) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

type EditEvent struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	User                 string   `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Operation            string   `protobuf:"bytes,4,opt,name=operation,proto3" json:"operation,omitempty"`
	Delta                string   `protobuf:"bytes,5,opt,name=delta,proto3" json:"delta,omitempty"`
	Timestamp            string   `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditEvent) Reset()         { *m = EditEvent{} }
func (m *EditEvent) String() string { return proto.CompactTextString(m) }
func (*EditEvent) ProtoMessage()    {}
func (*EditEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c88e0126701e74a, []int{1}
}

func (m *EditEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditEvent.Unmarshal(m, b)
}
func (m *EditEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditEvent.Marshal(b, m, deterministic)
}
func (m *EditEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditEvent.Merge(m, src)
}
func (m *EditEvent) XXX_Size() int {
	return xxx_messageInfo_EditEvent.Size(m)
}
func (m *EditEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_EditEvent.DiscardUnknown(m)
}

var xxx_messageInfo_EditEvent proto.InternalMessageInfo

func (m *EditEvent) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *EditEvent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EditEvent) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *EditEvent) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *EditEvent) GetDelta() string {
	if m != nil {
		return m.Delta
	}
	return ""
}

func (m *EditEvent) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

type CreateEventRequest struct {
	CreateEvent          *CreateEvent `protobuf:"bytes,1,opt,name=createEvent,proto3" json:"createEvent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateEventRequest) Reset()         { *m = CreateEventRequest{} }
func (m *CreateEventRequest) String() string { return proto.CompactTextString(m) }
func (*CreateEventRequest) ProtoMessage()    {}
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c88e0126701e74a, []int{2}
}

func (m *CreateEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEventRequest.Unmarshal(m, b)
}
func (m *CreateEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEventRequest.Marshal(b, m, deterministic)
}
func (m *CreateEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEventRequest.Merge(m, src)
}
func (m *CreateEventRequest) XXX_Size() int {
	return xxx_messageInfo_CreateEventRequest.Size(m)
}
func (m *CreateEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEventRequest proto.InternalMessageInfo

func (m *CreateEventRequest) GetCreateEvent() *CreateEvent {
	if m != nil {
		return m.CreateEvent
	}
	return nil
}

type CreateEventResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEventResponse) Reset()         { *m = CreateEventResponse{} }
func (m *CreateEventResponse) String() string { return proto.CompactTextString(m) }
func (*CreateEventResponse) ProtoMessage()    {}
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c88e0126701e74a, []int{3}
}

func (m *CreateEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEventResponse.Unmarshal(m, b)
}
func (m *CreateEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEventResponse.Marshal(b, m, deterministic)
}
func (m *CreateEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEventResponse.Merge(m, src)
}
func (m *CreateEventResponse) XXX_Size() int {
	return xxx_messageInfo_CreateEventResponse.Size(m)
}
func (m *CreateEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEventResponse proto.InternalMessageInfo

func (m *CreateEventResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type EditEventRequest struct {
	EditEvent            *EditEvent `protobuf:"bytes,1,opt,name=editEvent,proto3" json:"editEvent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EditEventRequest) Reset()         { *m = EditEventRequest{} }
func (m *EditEventRequest) String() string { return proto.CompactTextString(m) }
func (*EditEventRequest) ProtoMessage()    {}
func (*EditEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c88e0126701e74a, []int{4}
}

func (m *EditEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditEventRequest.Unmarshal(m, b)
}
func (m *EditEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditEventRequest.Marshal(b, m, deterministic)
}
func (m *EditEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditEventRequest.Merge(m, src)
}
func (m *EditEventRequest) XXX_Size() int {
	return xxx_messageInfo_EditEventRequest.Size(m)
}
func (m *EditEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditEventRequest proto.InternalMessageInfo

func (m *EditEventRequest) GetEditEvent() *EditEvent {
	if m != nil {
		return m.EditEvent
	}
	return nil
}

type EditEventResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditEventResponse) Reset()         { *m = EditEventResponse{} }
func (m *EditEventResponse) String() string { return proto.CompactTextString(m) }
func (*EditEventResponse) ProtoMessage()    {}
func (*EditEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c88e0126701e74a, []int{5}
}

func (m *EditEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditEventResponse.Unmarshal(m, b)
}
func (m *EditEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditEventResponse.Marshal(b, m, deterministic)
}
func (m *EditEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditEventResponse.Merge(m, src)
}
func (m *EditEventResponse) XXX_Size() int {
	return xxx_messageInfo_EditEventResponse.Size(m)
}
func (m *EditEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditEventResponse proto.InternalMessageInfo

func (m *EditEventResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateEvent)(nil), "event.CreateEvent")
	proto.RegisterType((*EditEvent)(nil), "event.EditEvent")
	proto.RegisterType((*CreateEventRequest)(nil), "event.CreateEventRequest")
	proto.RegisterType((*CreateEventResponse)(nil), "event.CreateEventResponse")
	proto.RegisterType((*EditEventRequest)(nil), "event.EditEventRequest")
	proto.RegisterType((*EditEventResponse)(nil), "event.EditEventResponse")
}

func init() { proto.RegisterFile("event/eventpb/event.proto", fileDescriptor_7c88e0126701e74a) }

var fileDescriptor_7c88e0126701e74a = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x25, 0xd0, 0x06, 0xe5, 0xca, 0x50, 0x0e, 0x04, 0x6e, 0xc5, 0x80, 0x3c, 0x55, 0x42, 0x04,
	0xa9, 0xb0, 0x32, 0x50, 0xd4, 0x85, 0xb1, 0x6c, 0x6c, 0x69, 0x7a, 0x83, 0xa5, 0x26, 0x36, 0xb6,
	0xd3, 0xef, 0x60, 0xe7, 0x67, 0x51, 0x6c, 0xa7, 0x49, 0x69, 0xc5, 0xc4, 0x92, 0xf8, 0xbd, 0x7b,
	0xbe, 0xf7, 0x7c, 0x3a, 0x18, 0xd1, 0x86, 0x4a, 0xfb, 0xe0, 0xbe, 0x6a, 0xe9, 0xff, 0xa9, 0xd2,
	0xd2, 0x4a, 0xec, 0x3b, 0xc0, 0x05, 0x0c, 0x5e, 0x35, 0x65, 0x96, 0xe6, 0x35, 0xc4, 0x4b, 0xe8,
	0x5b, 0xa9, 0x44, 0xce, 0xa2, 0xdb, 0x68, 0x92, 0x2c, 0x3c, 0x40, 0x84, 0x5e, 0x99, 0x15, 0xc4,
	0x8e, 0x1d, 0xe9, 0xce, 0x35, 0x57, 0x19, 0xd2, 0xec, 0xc4, 0x73, 0xf5, 0x19, 0x6f, 0x20, 0xb1,
	0xa2, 0x20, 0x63, 0xb3, 0x42, 0xb1, 0x9e, 0x2b, 0xb4, 0x04, 0xff, 0x8e, 0x20, 0x99, 0xaf, 0x84,
	0xfd, 0x27, 0x27, 0xa9, 0x48, 0x67, 0x56, 0xc8, 0xb2, 0x71, 0xda, 0x12, 0x75, 0xef, 0x15, 0xad,
	0x6d, 0xc6, 0xfa, 0xbe, 0xb7, 0x03, 0xbb, 0xe9, 0xe2, 0xdf, 0xe9, 0xde, 0x00, 0x3b, 0x83, 0x58,
	0xd0, 0x67, 0x45, 0xc6, 0xe2, 0x13, 0x0c, 0xf2, 0x96, 0x75, 0x59, 0x07, 0x53, 0x4c, 0xfd, 0x20,
	0xbb, 0xfa, 0xae, 0x8c, 0xdf, 0xc3, 0xc5, 0x4e, 0x2f, 0xa3, 0x64, 0x69, 0x08, 0xaf, 0x20, 0xd6,
	0x64, 0xaa, 0xb5, 0x0d, 0x6f, 0x0e, 0x88, 0xcf, 0x60, 0xb8, 0x9d, 0x4b, 0x63, 0x9c, 0x42, 0x42,
	0x0d, 0x17, 0x6c, 0x87, 0xc1, 0xb6, 0xd5, 0xb6, 0x12, 0x7e, 0x07, 0xe7, 0x9d, 0x1e, 0x7f, 0x1b,
	0x4e, 0xbf, 0x22, 0x38, 0x73, 0xca, 0x77, 0xd2, 0x1b, 0x91, 0x13, 0xbe, 0x40, 0xec, 0x03, 0xe3,
	0xe8, 0xc0, 0xdb, 0x7c, 0xa4, 0xf1, 0xf8, 0x50, 0xc9, 0x3b, 0xf1, 0x23, 0x7c, 0x86, 0x5e, 0x1d,
	0x00, 0xaf, 0xf7, 0x52, 0x86, 0xeb, 0x6c, 0xbf, 0xd0, 0x5c, 0x9e, 0x44, 0xb3, 0xe4, 0xe3, 0x34,
	0x6c, 0xe9, 0x32, 0x76, 0x0b, 0xfa, 0xf8, 0x13, 0x00, 0x00, 0xff, 0xff, 0x8b, 0xe6, 0xaa, 0x22,
	0xbd, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventServiceClient interface {
	// Create Feature Unary API
	Create(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (*CreateEventResponse, error)
	// Client Streaming
	Edit(ctx context.Context, opts ...grpc.CallOption) (EventService_EditClient, error)
}

type eventServiceClient struct {
	cc *grpc.ClientConn
}

func NewEventServiceClient(cc *grpc.ClientConn) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) Create(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (*CreateEventResponse, error) {
	out := new(CreateEventResponse)
	err := c.cc.Invoke(ctx, "/event.EventService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) Edit(ctx context.Context, opts ...grpc.CallOption) (EventService_EditClient, error) {
	stream, err := c.cc.NewStream(ctx, &_EventService_serviceDesc.Streams[0], "/event.EventService/Edit", opts...)
	if err != nil {
		return nil, err
	}
	x := &eventServiceEditClient{stream}
	return x, nil
}

type EventService_EditClient interface {
	Send(*EditEventRequest) error
	CloseAndRecv() (*EditEventResponse, error)
	grpc.ClientStream
}

type eventServiceEditClient struct {
	grpc.ClientStream
}

func (x *eventServiceEditClient) Send(m *EditEventRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *eventServiceEditClient) CloseAndRecv() (*EditEventResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(EditEventResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EventServiceServer is the server API for EventService service.
type EventServiceServer interface {
	// Create Feature Unary API
	Create(context.Context, *CreateEventRequest) (*CreateEventResponse, error)
	// Client Streaming
	Edit(EventService_EditServer) error
}

func RegisterEventServiceServer(s *grpc.Server, srv EventServiceServer) {
	s.RegisterService(&_EventService_serviceDesc, srv)
}

func _EventService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).Create(ctx, req.(*CreateEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_Edit_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EventServiceServer).Edit(&eventServiceEditServer{stream})
}

type EventService_EditServer interface {
	SendAndClose(*EditEventResponse) error
	Recv() (*EditEventRequest, error)
	grpc.ServerStream
}

type eventServiceEditServer struct {
	grpc.ServerStream
}

func (x *eventServiceEditServer) SendAndClose(m *EditEventResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *eventServiceEditServer) Recv() (*EditEventRequest, error) {
	m := new(EditEventRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _EventService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "event.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _EventService_Create_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Edit",
			Handler:       _EventService_Edit_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "event/eventpb/event.proto",
}
